version: '3'
services:
  epm-adapter-docker-compose:
    container_name: elastest-epm-adapter-docker-compose
    image: elastest/epm-adapter-docker-compose
    environment:
      - EPM_HOST=${EPM_HOST}
      - EPM_WORKER=${EPM_WORKER}
    entrypoint: python run.py --register-pop ${EPM_HOST} ${EPM_WORKER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - 50051:50051
