version: '2.1'
services:
    rabbitmq:
        container_name: rabbitmq-server
        build: services/rabbitmq
        image: services/rabbitmq
        env_file:
            - services/env
        expose:
            - 15672
            - 5672
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - elastest
    kibana:
        container_name: kibana-server
        build: services/kibana/
        image: services/kibana
        env_file:
          - services/env
        ports:
          - 5601:5601
        networks:
          - elastest
        links:
          - elasticsearch
    elasticsearch:
        container_name: elasticsearch-server
        build: services/elasticsearch
        image: services/elasticsearch
        env_file:
            - services/env
        expose:
            - 9200
            - 9300
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - elastest
        links:
            - rabbitmq
    logstash:
        container_name: logstash-server
        build: services/logstash
        image: services/logstash
        env_file:
            - services/env
        expose:
            - 5044
            - 5000
            - 9600
        ports:
            - 9600:9600
            - 5044:5044
            - 5000:5000
        networks:
            - elastest
        links:
            - elasticsearch
            - rabbitmq
    dockbeat:
        container_name: dockbeat-server
        build: services/dockbeat
        image: services/dockbeat
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        env_file:
            - services/env
        networks:
            - elastest
        links:
            - elasticsearch
    elastest-platform-manager:
        container_name: elastest-epm
        image: elastest/epm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        expose:
            - 8180
        ports:
            - 8180:8180
        networks:
            - elastest
        links:
            - logstash
            - dockbeat
    epm-adapter-docker-compose:
        container_name: elastest-epm-adapter-docker-compose
        image: elastest/epm-adapter-docker-compose
        entrypoint: python run.py --register-adapter
        depends_on:
            - elastest-platform-manager
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        ports:
            - 50051:50051
        networks:
            - elastest
networks:
    elastest:
        driver: bridge