version: '3'
services:
    elastest-platform-manager:
        container_name: elastest-epm
        build: ./docker/elastest-platform-manager
        image: elastest/epm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - KEYSTONE_ENDPOINT=http://10.147.65.101
            - KEYSTONE_PORT=35357
            - KEYSTONE_VERSION=v3
            - KEYSTONE_USERNAME=admin
            - KEYSTONE_PASSWORD=admin
            - KEYSTONE_DOMAIN=Default
            - KEYSTONE_ENABLED=true
        expose:
            - 8180
        ports:
            - 8180:8180
            - 50050:50050
        networks:
            - build-image-network
    epm-adapter-docker-compose:
        container_name: elastest-epm-adapter-docker-compose
        image: elastest/epm-adapter-docker-compose
        entrypoint: python run.py --register-adapter
        depends_on:
            - elastest-platform-manager
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        ports:
            - 50051:50051
        networks:
            - build-image-network
    aaa:
        depends_on:
          - mysql
        image: dizz/dock-os-keystone
        hostname: aaa
        container_name: aaa
        links:
          - mysql
        ports:
          - "35357:35357"
          - "5000:5000"
        environment:
          MYSQL_HOST: mysql
          MYSQL_ROOT_PASSWORD: shush  # XXX there's an issue here: if set connections get reset
          ADMIN_TOKEN: admintokin
          ADMIN_TENANT_NAME: admin
          ADMIN_USER_NAME: admin
          ADMIN_PASSWORD: admin
        networks:
          - elastest_elastest
                

    mysql:
        image: mysql:5.7
        container_name: mysql
        hostname: mysql
        environment:
          MYSQL_ROOT_PASSWORD: shush
        ports:
          - "3306"
        healthcheck:  # required in order to signal correct startup to dependent services (see aaa)
          test: "/usr/bin/mysql --user=root --password=shush --execute \"show databases;\""
          interval: 10s
          timeout: 10s
          retries: 5
        networks:
          - elastest_elastest
networks:
    build-image-network:
        driver: bridge
    elastest_elastest:
        driver: bridge


