version: '3'
services:
  epm-adapter-docker-compose:
    container_name: elastest-epm-adapter-docker-compose
    image: elastest/epm-adapter-docker-compose
    entrypoint: python run.py --register-adapter ${EPM_HOST} ${EPM_WORKER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - 50051:50051

  system-agent:
      image: elastest/emp-system-agent:latest
      hostname: ${WORKER_NAME}
      environment:
        - KAFKA_ENDPOINT=${KAFKA_ENDPOINT}
        - KAFKA_KEY_SERIALIZER=StringSerializer
        - KAFKA_VALUE_SERIALIZER=StringSerializer
        - SENTINEL_TOPIC=${SENTINEL_TOPIC}
        - SENTINEL_SERIES=${SENTINEL_SERIES}
        - PERIODICITY=60